name: Deploy HTML to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show all files in workspace
        run: ls -al

      - name: Upload files to EC2 (/home/ubuntu)
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "./*"
          target: "/home/ubuntu/"

      - name: SSH into EC2 and move files to /var/www/html
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo rm -rf /var/www/html/*
            sudo cp -r /home/ubuntu/* /var/www/html/
            sudo chown -R www-data:www-data /var/www/html/
            sudo systemctl restart nginx
